version: '3.9'
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    healthcheck:
      test: curl http://localhost:8080/corpus || exit 1
      interval: 10s
      retries: 5
  frontend-export:
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8080/
      - NEXT_PUBLIC_READONLY=true
    build:
      context: frontend
      dockerfile: export.dockerfile
    volumes:
      - type: bind
        source: ./export
        target: /app/out
