import '@mantine/core/styles.css'
import '@/styles/globals.css'
import {MantineProvider} from "@mantine/core";
import {useRouter} from "next/router";
import {GlobalStateContext, GraphContext} from "@/components/Contexts";
import {allowEdit} from "../api";

export default function App({ Component, pageProps }) {
  const router = useRouter()
  const generationDate = new Date()

  const content = <>
    <Component {...pageProps} />
    {!allowEdit() && <div className="footer">Generated by <a href="https://github.com/yole/etymograph">yole/etymograph</a> on {generationDate.toDateString()}</div>}
  </>

  return <MantineProvider>
    <GraphContext.Provider value={router.query.graph}>
      {pageProps.globalState !== undefined && <GlobalStateContext.Provider value={pageProps.globalState}>
        {content}
      </GlobalStateContext.Provider>}
      {pageProps.globalState === undefined && content}
    </GraphContext.Provider>
  </MantineProvider>
}
