import '@mantine/core/styles.css'
import '@/styles/globals.css'
import {MantineProvider} from "@mantine/core";
import {useRouter} from "next/router";
import {AuthContext, GlobalStateContext, GraphContext} from "@/components/Contexts";
import {hasBackend, fetchAuthStatus} from "../api";
import {useEffect, useState} from "react";

export default function App({ Component, pageProps }) {
  const router = useRouter()
  const generationDate = new Date()
  const [authStatus, setAuthStatus] = useState()

  useEffect(() => {
    if (typeof window === "undefined" || hasBackend() === false) {
      return
    }

    fetchAuthStatus()
        .then(setAuthStatus)
        .catch(() => setAuthStatus(undefined))
  }, [])

  const content = <>
    <Component {...pageProps} />
    {!hasBackend() && <div className="footer">Generated by <a href="https://github.com/yole/etymograph">yole/etymograph</a> on {generationDate.toDateString()}</div>}
  </>

  return <MantineProvider>
    <GraphContext.Provider value={router.query.graph}>
      <AuthContext.Provider value={{authStatus}}>
        {pageProps.globalState !== undefined && <GlobalStateContext.Provider value={pageProps.globalState}>
          {content}
        </GlobalStateContext.Provider>}
        {pageProps.globalState === undefined && content}
      </AuthContext.Provider>
    </GraphContext.Provider>
  </MantineProvider>
}
