// This file is auto-generated by @hey-api/openapi-ts

export type AcceptAlternativeParameters = {
    index: number;
    wordId: number;
    ruleId: number;
};

export type AddPublicationParameters = {
    name?: (string) | null;
    refId?: (string) | null;
    author?: (string) | null;
    date?: (string) | null;
    publisher?: (string) | null;
};

export type AddWordParameters = {
    text?: (string) | null;
    gloss?: (string) | null;
    fullGloss?: (string) | null;
    pos?: (string) | null;
    classes?: (string) | null;
    reconstructed?: (boolean) | null;
    syllabographic?: (boolean) | null;
    source?: (string) | null;
    notes?: (string) | null;
    forceNew?: (boolean) | null;
};

export type AlternativeViewModel = {
    gloss: string;
    wordId: number;
    ruleId: number;
};

export type ApplySequenceParams = {
    linkFromId: number;
    linkToId: number;
};

export type AssociateWordParameters = {
    index: number;
    wordId: number;
    contextGloss?: (string) | null;
};

export type AttestationViewModel = {
    textId: number;
    textTitle: string;
    word?: (string) | null;
};

export type ComparePhonemesParameters = {
    toPhoneme: string;
};

export type ComparePhonemesResult = {
    message: string;
};

export type CompoundComponentsViewModel = {
    compoundId: number;
    components: Array<WordRefViewModel>;
    headIndex?: (number) | null;
    derivation: boolean;
    source: Array<SourceRefViewModel>;
    sourceEditableText: string;
    notes?: (string) | null;
};

export type CompoundParams = {
    compoundId: number;
    firstComponentId: number;
    head?: (number) | null;
    source?: (string) | null;
    notes?: (string) | null;
};

export type CopyPhonemesParams = {
    fromLang: string;
};

export type CorpusLangTextViewModel = {
    id: number;
    title: string;
};

export type CorpusLangViewModel = {
    language: Language;
    corpusTexts: Array<CorpusLangTextViewModel>;
};

export type CorpusLineViewModel = {
    words: Array<CorpusWordViewModel>;
};

export type CorpusTextParams = {
    title: string;
    text: string;
    source: string;
    notes: string;
};

export type CorpusTextViewModel = {
    id: number;
    title: string;
    language: string;
    languageFullName: string;
    text: string;
    lines: Array<CorpusLineViewModel>;
    source: Array<SourceRefViewModel>;
    sourceEditableText: string;
    notes?: (string) | null;
    translations: Array<TranslationViewModel>;
};

export type CorpusWordCandidateViewModel = {
    id: number;
    gloss?: (string) | null;
};

export type CorpusWordViewModel = {
    index: number;
    text: string;
    normalizedText: string;
    gloss: string;
    contextGloss?: (string) | null;
    wordId?: (number) | null;
    wordText?: (string) | null;
    wordCandidates?: Array<CorpusWordCandidateViewModel> | null;
    stressIndex?: (number) | null;
    stressLength?: (number) | null;
    homonym: boolean;
};

export type DerivationViewModel = {
    baseWord: WordRefViewModel;
    derivation: LinkWordViewModel;
    expectedWord?: (string) | null;
    singlePhonemeDifference?: (string) | null;
    pos?: (string) | null;
};

export type DeriveThroughSequenceParams = {
    sequenceId: number;
};

export type DictionaryViewModel = {
    language: Language;
    words: Array<DictionaryWordViewModel>;
    wordsByLetter?: (string) | null;
};

export type DictionaryWordViewModel = {
    id: number;
    text: string;
    gloss: string;
    fullGloss?: (string) | null;
    homonym: boolean;
    pos?: (string) | null;
};

export type GenerateParadigmParameters = {
    name: string;
    lang: string;
    pos: string;
    addedCategories: string;
    prefix: string;
    rows: string;
    columns: string;
};

export type GraphViewModel = {
    id: string;
    name: string;
};

export type InputAssistGraphemeViewModel = {
    text: string;
    languages: Array<(string)>;
};

export type InputAssistViewModel = {
    graphemes: Array<InputAssistGraphemeViewModel>;
};

export type Language = {
    name: string;
    shortName: string;
    reconstructed: boolean;
    protoLanguage?: (Language) | null;
    phonemes?: Array<Phoneme> | null;
    diphthongs: Array<(string)>;
    syllableStructures: Array<(string)>;
    stressRule?: (RuleRef) | null;
    phonotacticsRule?: (RuleRef) | null;
    pronunciationRule?: (RuleRef) | null;
    orthographyRule?: (RuleRef) | null;
    pos?: Array<WordCategoryValue> | null;
    grammaticalCategories?: Array<WordCategory> | null;
    wordClasses?: Array<WordCategory> | null;
    accentTypes?: Array<('Acute' | 'Grave' | 'Circumflex')> | null;
    orthoPhonemeLookup?: (PhonemeLookup) | null;
    phonoPhonemeLookup?: (PhonemeLookup) | null;
    dictionarySettings?: (string) | null;
};

export type LanguageShortViewModel = {
    name: string;
    shortName: string;
    protoLanguageShortName?: (string) | null;
    pos: Array<WordCategoryValueViewModel>;
    wordClasses: Array<WordCategoryViewModel>;
    dictionaries: Array<(string)>;
    descendantLanguages?: Array<LanguageShortViewModel> | null;
};

export type LanguageViewModel = {
    name: string;
    shortName: string;
    protoLanguageShortName?: (string) | null;
    reconstructed: boolean;
    diphthongs: Array<(string)>;
    phonemes: Array<PhonemeTableViewModel>;
    stressRuleId?: (number) | null;
    stressRuleName?: (string) | null;
    phonotacticsRuleId?: (number) | null;
    phonotacticsRuleName?: (string) | null;
    pronunciationRuleId?: (number) | null;
    pronunciationRuleName?: (string) | null;
    orthographyRule?: (RuleRefViewModel) | null;
    syllableStructures: Array<(string)>;
    pos: string;
    grammaticalCategories: string;
    wordClasses: string;
    dictionarySettings?: (string) | null;
    accentTypes: Array<(string)>;
};

export type LinkedRuleViewModel = {
    ruleId: number;
    ruleName: string;
    linkType: string;
    source: Array<SourceRefViewModel>;
    notes?: (string) | null;
};

export type LinkParams = {
    fromEntity: number;
    toEntity: number;
    linkType: string;
    ruleNames: string;
    source: string;
    notes?: (string) | null;
};

export type LinkTypeViewModel = {
    typeId: string;
    type: string;
    words: Array<LinkWordViewModel>;
};

export type LinkWordViewModel = {
    word: WordRefViewModel;
    ruleIds: Array<(number)>;
    ruleNames: Array<(string)>;
    ruleResults: Array<(string)>;
    ruleSequence?: (WordRuleSequenceViewModel) | null;
    source: Array<SourceRefViewModel>;
    sourceEditableText: string;
    notes?: (string) | null;
    suggestedSequences: Array<WordRuleSequenceViewModel>;
};

export type LookupParameters = {
    dictionaryId: string;
    disambiguation?: (string) | null;
};

export type LookupResultViewModel = {
    status?: (string) | null;
    variants: Array<LookupVariantViewModel>;
};

export type LookupVariantViewModel = {
    text: string;
    disambiguation?: (string) | null;
};

export type ParadigmCellViewModel = {
    alternativeRuleNames: Array<(string)>;
    alternativeRuleSummaries: Array<(string)>;
    alternativeRuleIds: Array<(number)>;
};

export type ParadigmColumnViewModel = {
    title: string;
    cells: Array<ParadigmCellViewModel>;
};

export type ParadigmRefViewModel = {
    id: number;
    name: string;
    refType: string;
};

export type ParadigmViewModel = {
    id: number;
    name: string;
    language: string;
    languageFullName: string;
    pos: Array<(string)>;
    rowTitles: Array<(string)>;
    columns: Array<ParadigmColumnViewModel>;
    editableText: string;
    preRule?: (RuleRefViewModel) | null;
    postRule?: (RuleRefViewModel) | null;
};

export type ParseCandidatesViewModel = {
    parseCandidates: Array<ParseCandidateViewModel>;
};

export type ParseCandidateViewModel = {
    text: string;
    categories: string;
    ruleNames: Array<(string)>;
    pos?: (string) | null;
    wordId?: (number) | null;
};

export type Phoneme = {
    graphemes: Array<(string)>;
    sound?: (string) | null;
    classes: Array<(string)>;
    historical: boolean;
    id: number;
    source: Array<SourceRef>;
    notes?: (string) | null;
};

export type PhonemeLookup = {
    accentTypes: Array<('Acute' | 'Grave' | 'Circumflex')>;
};

export type PhonemeRuleGroupViewModel = {
    title: string;
    rules: Array<PhonemeRuleViewModel>;
};

export type PhonemeRuleViewModel = {
    id: number;
    name: string;
    summary: string;
};

export type PhonemeTableCellViewModel = {
    phonemes: Array<PhonemeViewModel>;
};

export type PhonemeTableRowViewModel = {
    title: string;
    cells: Array<PhonemeTableCellViewModel>;
};

export type PhonemeTableViewModel = {
    title: string;
    columnTitles: Array<(string)>;
    rows: Array<PhonemeTableRowViewModel>;
};

export type PhonemeViewModel = {
    id: number;
    languageShortName: string;
    languageFullName: string;
    graphemes: Array<(string)>;
    sound: string;
    classes: string;
    implicitClasses: string;
    features: string;
    historical: boolean;
    source: Array<SourceRefViewModel>;
    sourceEditableText: string;
    notes?: (string) | null;
    relatedRules: Array<PhonemeRuleGroupViewModel>;
};

export type PublicationViewModel = {
    id: number;
    name: string;
    author?: (string) | null;
    date?: (string) | null;
    publisher?: (string) | null;
    refId: string;
};

export type ReapplyResultViewModel = {
    consistent: number;
    becomesConsistent: Array<WordRefViewModel>;
    becomesInconsistent: Array<WordRefViewModel>;
    inconsistent: number;
};

export type RichText = {
    fragments: Array<RichTextFragment>;
};

export type RichTextFragment = {
    text: string;
    tooltip?: (string) | null;
    emph: boolean;
    subscript: boolean;
    monospaced: boolean;
    linkType?: (string) | null;
    linkId?: (number) | null;
    linkLanguage?: (string) | null;
    linkData?: (string) | null;
};

export type RuleBranchViewModel = {
    conditions: RichText;
    instructions: Array<RichText>;
    comment?: (string) | null;
    examples: Array<RuleExampleViewModel>;
};

export type RuleExampleViewModel = {
    fromWord: WordRefViewModel;
    toWord: WordRefViewModel;
    expectedWord?: (string) | null;
    wordBeforeRule?: (string) | null;
    wordAfterRule?: (string) | null;
};

export type RuleGroupViewModel = {
    groupName: string;
    rules: Array<RuleShortViewModel>;
    sequenceId?: (number) | null;
    sequenceName?: (string) | null;
    sequenceFromLang?: (string) | null;
    sequenceToLang?: (string) | null;
    paradigmId?: (number) | null;
};

export type RuleLinkParams = {
    fromEntity: number;
    toRuleName: string;
    linkType: string;
    source: string;
    notes?: (string) | null;
};

export type RuleLinkViewModel = {
    toRuleId: number;
    toRuleName: string;
    linkType: string;
    source: Array<SourceRefViewModel>;
    notes?: (string) | null;
};

export type RuleListViewModel = {
    toLangFullName: string;
    ruleGroups: Array<RuleGroupViewModel>;
};

export type RulePreviewParams = {
    newText: string;
};

export type RulePreviewResultListViewModel = {
    results: Array<RulePreviewResultViewModel>;
};

export type RulePreviewResultViewModel = {
    word: WordRefViewModel;
    oldForm: string;
    newForm: string;
};

export type RuleRef = {
    [key: string]: unknown;
};

export type RuleRefViewModel = {
    id: number;
    name: string;
};

export type RuleSequenceLinkViewModel = {
    sequenceName: string;
    prev?: (RuleRefViewModel) | null;
    next?: (RuleRefViewModel) | null;
};

export type RuleSequenceViewModel = {
    id: number;
    name: string;
    fromLang: string;
    toLang: string;
};

export type RuleShortViewModel = {
    id: number;
    name: string;
    toLang: string;
    alternative?: (RuleRefViewModel) | null;
    summaryText: string;
    optional: boolean;
    dispreferred: boolean;
};

export type RuleTraceParams = {
    word: string;
    language?: (string) | null;
    reverse: boolean;
};

export type RuleTraceResult = {
    trace: string;
    result: string;
};

export type RuleViewModel = {
    id: number;
    name: string;
    fromLang: string;
    toLang: string;
    fromLangFullName: string;
    toLangFullName: string;
    summaryText: string;
    editableText: string;
    addedCategories?: (string) | null;
    replacedCategories?: (string) | null;
    addedCategoryDisplayNames?: (string) | null;
    fromPOS: Array<(string)>;
    toPOS?: (string) | null;
    source: Array<SourceRefViewModel>;
    sourceEditableText: string;
    notes?: (string) | null;
    paradigmId?: (number) | null;
    paradigmName?: (string) | null;
    paradigmPreRule?: (RuleRefViewModel) | null;
    paradigmPostRule?: (RuleRefViewModel) | null;
    spe: boolean;
    preInstructions: Array<RichText>;
    branches: Array<RuleBranchViewModel>;
    postInstructions: Array<RichText>;
    links: Array<RuleLinkViewModel>;
    references: Array<RuleRefViewModel>;
    sequenceLinks: Array<RuleSequenceLinkViewModel>;
    linkedWords: Array<RuleWordLinkViewModel>;
    orphanExamples: Array<RuleExampleViewModel>;
    referencingParadigms: Array<ParadigmRefViewModel>;
};

export type RuleWordLinkViewModel = {
    toWord: WordRefViewModel;
    linkType: string;
    source: Array<SourceRefViewModel>;
    notes?: (string) | null;
};

export type SearchResponse = {
    totalExact: number;
    totalPrefix: number;
    matches: Array<WordRefViewModel>;
    usedMode: string;
};

export type SequenceDerivationsViewModel = {
    sequence: RuleSequenceViewModel;
    derivations: Array<DerivationViewModel>;
};

export type SequenceReportViewModel = {
    name: string;
    toLang: string;
    rules: Array<SequenceRuleViewModel>;
};

export type SequenceRuleViewModel = {
    ruleName: string;
    ruleSource: string;
    ruleIsSPE: boolean;
    optional: boolean;
    dispreferred: boolean;
    alternativeRuleName?: (string) | null;
    preInstructions: Array<RichText>;
    branches: Array<RuleBranchViewModel>;
    postInstructions: Array<RichText>;
};

export type SourceRef = {
    pubId?: (number) | null;
    refText: string;
};

export type SourceRefViewModel = {
    pubId?: (number) | null;
    pubRefId?: (string) | null;
    refText: string;
};

export type SuggestCompoundParameters = {
    compoundId?: (number) | null;
};

export type SuggestCompoundViewModel = {
    suggestions: Array<WordRefViewModel>;
};

export type TranslationParams = {
    corpusTextId?: (number) | null;
    text: string;
    source: string;
};

export type TranslationViewModel = {
    id: number;
    text: string;
    source: Array<SourceRefViewModel>;
    sourceEditableText: string;
};

export type UpdateCompoundParams = {
    componentId: number;
    markHead: boolean;
};

export type UpdateLanguageParameters = {
    name?: (string) | null;
    shortName?: (string) | null;
    protoLanguageShortName?: (string) | null;
    reconstructed?: (boolean) | null;
    phonemes?: (string) | null;
    diphthongs?: (string) | null;
    stressRuleName?: (string) | null;
    phonotacticsRuleName?: (string) | null;
    pronunciationRuleName?: (string) | null;
    orthographyRuleName?: (string) | null;
    syllableStructures?: (string) | null;
    pos?: (string) | null;
    grammaticalCategories?: (string) | null;
    wordClasses?: (string) | null;
    dictionarySettings?: (string) | null;
    accentTypes?: Array<(string)> | null;
};

export type UpdateParadigmParameters = {
    name: string;
    pos: string;
    text: string;
    preRuleName?: (string) | null;
    postRuleName?: (string) | null;
};

export type UpdatePhonemeParameters = {
    graphemes: string;
    sound: string;
    classes: string;
    historical: boolean;
    source?: (string) | null;
    notes?: (string) | null;
};

export type UpdateRuleParameters = {
    name: string;
    fromLang: string;
    toLang: string;
    text: string;
    addedCategories?: (string) | null;
    replacedCategories?: (string) | null;
    fromPOS?: (string) | null;
    toPOS?: (string) | null;
    source?: (string) | null;
    notes?: (string) | null;
    addToSequenceId?: (number) | null;
};

export type UpdateSequenceParams = {
    name: string;
    fromLang: string;
    toLang: string;
    ruleNames: string;
};

export type UpdateWordParadigmParameters = {
    items: Array<(unknown[])>;
};

export type WordCategory = {
    name: string;
    pos: Array<(string)>;
    values: Array<WordCategoryValue>;
};

export type WordCategoryValue = {
    name: string;
    abbreviation: string;
};

export type WordCategoryValueViewModel = {
    name: string;
    abbreviation: string;
};

export type WordCategoryViewModel = {
    name: string;
    pos: Array<(string)>;
    values: Array<WordCategoryValueViewModel>;
};

export type WordParadigmListModel = {
    word: string;
    wordId: number;
    language: string;
    languageFullName: string;
    paradigms: Array<WordParadigmModel>;
};

export type WordParadigmModel = {
    name: string;
    rowTitles: Array<(string)>;
    columnTitles: Array<(string)>;
    cells: Array<(unknown[])>;
};

export type WordRefViewModel = {
    id: number;
    text: string;
    language: string;
    displayLanguage: string;
    gloss?: (string) | null;
    homonym: boolean;
    reconstructed: boolean;
};

export type WordRuleSequenceViewModel = {
    name: string;
    id: number;
};

export type WordSequenceParams = {
    sequence: string;
    source: string;
};

export type WordSequenceResults = {
    words: Array<WordRefViewModel>;
    ruleIds: Array<(number)>;
};

export type WordViewModel = {
    id: number;
    language: string;
    languageFullName: string;
    languageReconstructed: boolean;
    text: string;
    textWithExplicitStress: string;
    gloss: string;
    glossComputed: boolean;
    fullGloss?: (string) | null;
    pos?: (string) | null;
    classes: Array<(string)>;
    reconstructed: boolean;
    syllabographic: boolean;
    source: Array<SourceRefViewModel>;
    sourceEditableText: string;
    notes?: (string) | null;
    attestations: Array<AttestationViewModel>;
    linksFrom: Array<LinkTypeViewModel>;
    linksTo: Array<LinkTypeViewModel>;
    compounds: Array<WordRefViewModel>;
    derivationalCompounds: Array<WordRefViewModel>;
    components: Array<CompoundComponentsViewModel>;
    linkedRules: Array<LinkedRuleViewModel>;
    stressIndex?: (number) | null;
    stressLength?: (number) | null;
    compound: boolean;
    hasParadigms: boolean;
    suggestedDeriveSequences: Array<WordRuleSequenceViewModel>;
};