name: Run backend tests
on: [push, workflow_dispatch]
jobs:
  publish:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2

      - name: Test
        run: ./gradlew test
