name: Publish read-only database for Elvish
on: [push, workflow_dispatch]
jobs:
  export-database:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start backend
        run: docker compose up backend --build --detach --wait

      - name: Create export target directory
        run: mkdir export

      - name: Generate exported data
        run: docker compose up frontend-export

      - name: Publish to Netlify
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.ELVISH_ETYMOGRAPH_SITE_ID }}
          NETLIFY_DIR: export

      - name: Show logs
        if: always()
        run: docker logs etymograph-backend-1

      - name: Inspect health check
        if: always()
        run: docker inspect etymograph-backend-1

      - name: Stop containers
        if: always()
        run: docker compose down
