name: Publish read-only database
on:
  workflow_call:
    inputs:
      graphPath:
        required: true
        type: string
    secrets:
      netlifyAuthToken:
        required: true
      siteId:
        required: true
jobs:
  export-database:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start backend
        run: docker compose up backend --build --detach --wait
        env:
          ETYMOGRAPH_GRAPH_PATH: ${{ inputs.graphPath }}

      - name: Create export target directory
        run: mkdir export

      - name: Generate exported data
        run: docker compose up --build frontend-export

      - name: Publish to Netlify
        uses: South-Paw/action-netlify-cli@v2
        with:
          args: deploy --dir=export/out --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.netlifyAuthToken }}
          NETLIFY_SITE_ID: ${{ secrets.siteId }}

      - name: Show logs
        if: always()
        run: docker logs etymograph-backend-1

      - name: Inspect health check
        if: always()
        run: docker inspect etymograph-backend-1

      - name: Stop containers
        if: always()
        run: docker compose down
