name: Publish read-only database
on: [push, workflow_dispatch]
jobs:
  publish-database:
    uses: ./.github/workflows/etymograph-build.yml
    with:
      graphPath: /app/ie,/app/jrrt
    secrets:
      siteId: ${{ secrets.ETYMOGRAPH_SITE_ID }}
      netlifyAuthToken: ${{ secrets.NETLIFY_AUTH_TOKEN }}
